### ISSUE TITLE
Radeon Pro 580X on MacOS support

### ISSUE THREAD

**Issue by vschwaberow** [CompVis/stable-diffusion#319]
Any way to use the Radeon Pro 580X GPU for stable diffusion?

**Comment by dutch2005** [comment]
https://pythoninoffice.com/run-stable-diffusion-amd-gpu-on-windows/

https://www.youtube.com/watch?v=Lk2syPsVMQM&

Similar steps are to be taken for MacOS (just install the MacOS versions of the listed applications).

Oh and make sure GIT is installed.

**Comment by Jorginthesage** [comment]
The diffusers library is for windows and won’t install on MacOSX with PIP….

**Comment by viking1304** [comment]
I know this is a very old and closed issue, but I will add my comment here in case someone else has this problem and needs a working solution.

You can use the initial setup (first 3 steps) described [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/5461)

and then proceed with the [instructions](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/5461#discussioncomment-7557406) I posted in the same thread.

As I wrote, the same setup works for both Silicon and Intel Macs. Even those with Radeon, since Macs with Radeon also use metal. I have tested everything on both M1 and iMac with Radeon Pro 580X.
