### ISSUE TITLE
why badcase ? 

### ISSUE THREAD

**Issue by dushwe** [CompVis/stable-diffusion#339]
when W:H not 1:1.  What caused this bad case ? 
![image](https://user-images.githubusercontent.com/19389452/193182535-4068c655-1b35-4372-81b7-d6f6c2a43d0a.png)

**Comment by dlondero** [comment]
Interesting. What was the prompt for such a result?

**Comment by dlondero** [comment]
Also with same prompt and seed with W:H 1:1 what do you get?

**Comment by CryptoEconomize** [comment]
I get lots of these with the H 768 x W 512 generations and then if using H 512 x W 768 it results in some duplications of images horizontally.  I think most of the generations are fine but there seems to be a lot of models that only work well with 512 x 512 because that's likely what they were trained on.
