### ISSUE TITLE
torch.cuda.OutOfMemoryError

### ISSUE THREAD

**Issue by hunain7867** [CompVis/stable-diffusion#656]
hello there so i just got into using stable diffusion I had a few previous problems like my sd was running on my integrated graphics I could rid of that issue by reinstalling the drivers and setting my GPU RTX 3050 4gb vram as my main graphic hardware. so now everything was smooth with creating images but then I wanted to make a textual inversion embedding of myself but when I tried to run it following Aitrepreneur's video I ran into this error I mean I haven't used my GPU before it said tried to allocate  96.00 MiB (GPU 0; 4.00 GiB total capacity; 3.25 GiB already allocated; 0 bytes free; 3.40 GiB reserved in total by PyTorch)  it says its already allocated what does it mean ? I know I'm a noob but from my understanding it requires 100mb but I have 4gb which is reserved how do I change that so that sd can use the reserved memory 
i apologize in advance for my stupidity 
oh and I am using automatic 1111 sd 

and it says " If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation." how do I do that should I just run it in a cmd window or git bash ?

here is the full message

" File "C:\ai\stable-diffusion-webui\modules\sd_hijack_optimizations.py", line 129, in split_cross_attention_forward
    s2 = s1.softmax(dim=-1, dtype=q.dtype)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 96.00 MiB (GPU 0; 4.00 GiB total capacity; 3.25 GiB already allocated; 0 bytes free; 3.40 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
"

**Comment by jenuk** [comment]
Allocated memory is the memory that is currently in use by pytorch to save the results of all the calculations happening. Likely some memory is used up by other things currently running on the computer, which would explain the difference between reserved memory, total capacity and free bytes).

I don't think the difference between reserved memory and allocated memory is large enough to bother with the max_split_size. You most likely will not be able to run textual inversion with that amount of VRAM (if you don't know of other people having done it with the same GPU). 

Since your question is actually about the [stable diffusion webui by AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui). You may want to look into the [issues](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues?q=is%3Aissue) there, both closed and open to find out if other people have reported this problem before, or open a new issue if that is not the case.
