### ISSUE TITLE
Impact of long prompts on GPU memory

### ISSUE THREAD

**Issue by ulysses500** [CompVis/stable-diffusion#679]
After making many generations with stable diffusion, I have noticed that long prompts significantly increase memory needs. 

Why is it so? Is there a way to measure the impact of prompts in terms of GPU memory?

**Comment by jenuk** [comment]
Prompt length does not affect memory requirements (in this codebase).

The input-text is tokenized and during that step every prompt is padded with special tokens so that each prompt has the exact same length, see [here](https://github.com/CompVis/stable-diffusion/blob/21f890f9da3cfbeaba8e2ac3c425ee9e998d5229/ldm/modules/encoders/modules.py#L152-L159). So the only difference between a short and a long prompt is what numbers are in the tensors, but not their shape. So everything still takes the same number of calculations and have the same memory need.

There are some scripts online that provide the ability to increase the prompt length past 75 tokens, it is expected that the memory need will increase in that case.
